In [1]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch as pt

In [3]:
# Empty matrix
x=pt.empty(3,3)
x

tensor([[-1.4942e-04,  4.5705e-41, -1.4942e-04],
        [ 4.5705e-41, -1.4941e-04,  4.5705e-41],
        [-1.4941e-04,  4.5705e-41, -8.0177e-05]])

In [4]:
# Randomly initialized matrix
x=pt.rand(3,3)
x

tensor([[0.8704, 0.3315, 0.6680],
        [0.9948, 0.8045, 0.4780],
        [0.1282, 0.7248, 0.0867]])

In [6]:
# Zeros matrix
x=pt.zeros(3,3,dtype=pt.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
# Construct a tensor directly from data
x=pt.tensor([3.5,3])
x

tensor([3.5000, 3.0000])

In [9]:
# size
print(x.size())

torch.Size([2])


In [12]:
# Changing numpy array to torch
import numpy as np
a=np.ones(5)
b=pt.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
